# Generated by Django 3.2.5 on 2022-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsdetails',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
